#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : kmail-account-wizard
Version  : 18.08.0
Release  : 2
URL      : https://download.kde.org/stable/applications/18.08.0/src/kmail-account-wizard-18.08.0.tar.xz
Source0  : https://download.kde.org/stable/applications/18.08.0/src/kmail-account-wizard-18.08.0.tar.xz
Source99 : https://download.kde.org/stable/applications/18.08.0/src/kmail-account-wizard-18.08.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GFDL-1.2 GPL-2.0 LGPL-2.1
Requires: kmail-account-wizard-bin
Requires: kmail-account-wizard-lib
Requires: kmail-account-wizard-data
Requires: kmail-account-wizard-license
Requires: kmail-account-wizard-locales
BuildRequires : akonadi-contacts-dev
BuildRequires : akonadi-dev
BuildRequires : akonadi-mime-dev
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : gpgme-dev
BuildRequires : gpgme-extras
BuildRequires : kcontacts-dev
BuildRequires : kidentitymanagement-dev
BuildRequires : kimap-dev
BuildRequires : kldap-dev
BuildRequires : kmailtransport-dev
BuildRequires : kmime-dev
BuildRequires : knotifyconfig-dev
BuildRequires : kpimtextedit-dev
BuildRequires : kross-dev
BuildRequires : ktexteditor-dev
BuildRequires : libassuan-dev
BuildRequires : libgpg-error-dev
BuildRequires : libkdepim-dev
BuildRequires : libkleo-dev
BuildRequires : pimcommon-dev
BuildRequires : qtbase-dev qtbase-extras mesa-dev
BuildRequires : shared-mime-info

%description
No detailed description available

%package bin
Summary: bin components for the kmail-account-wizard package.
Group: Binaries
Requires: kmail-account-wizard-data
Requires: kmail-account-wizard-license

%description bin
bin components for the kmail-account-wizard package.


%package data
Summary: data components for the kmail-account-wizard package.
Group: Data

%description data
data components for the kmail-account-wizard package.


%package lib
Summary: lib components for the kmail-account-wizard package.
Group: Libraries
Requires: kmail-account-wizard-data
Requires: kmail-account-wizard-license

%description lib
lib components for the kmail-account-wizard package.


%package license
Summary: license components for the kmail-account-wizard package.
Group: Default

%description license
license components for the kmail-account-wizard package.


%package locales
Summary: locales components for the kmail-account-wizard package.
Group: Default

%description locales
locales components for the kmail-account-wizard package.


%prep
%setup -q -n kmail-account-wizard-18.08.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535430967
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1535430967
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/kmail-account-wizard
cp COPYING %{buildroot}/usr/share/doc/kmail-account-wizard/COPYING
cp COPYING.DOC %{buildroot}/usr/share/doc/kmail-account-wizard/COPYING.DOC
cp COPYING.LIB %{buildroot}/usr/share/doc/kmail-account-wizard/COPYING.LIB
pushd clr-build
%make_install
popd
%find_lang accountwizard
%find_lang accountwizard_tine20

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/accountwizard
/usr/bin/ispdb

%files data
%defattr(-,root,root,-)
/usr/share/akonadi/accountwizard/tine20/tine20wizard.desktop
/usr/share/akonadi/accountwizard/tine20/tine20wizard.es
/usr/share/akonadi/accountwizard/tine20/tine20wizard.ui
/usr/share/applications/org.kde.accountwizard.desktop
/usr/share/mime/packages/accountwizard-mime.xml
/usr/share/xdg/accountwizard.categories
/usr/share/xdg/accountwizard.knsrc
/usr/share/xdg/accountwizard.renamecategories

%files lib
%defattr(-,root,root,-)
/usr/lib64/qt5/plugins/accountwizard_plugin.so

%files license
%defattr(-,root,root,-)
/usr/share/doc/kmail-account-wizard/COPYING
/usr/share/doc/kmail-account-wizard/COPYING.DOC
/usr/share/doc/kmail-account-wizard/COPYING.LIB

%files locales -f accountwizard.lang -f accountwizard_tine20.lang
%defattr(-,root,root,-)

